src/objects/Community_Profile_Tag__c.object
<CustomObject>
    <description>This object allows contacts to select Tags to define their interests in the Community.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allows tags to be associated to this Contact record.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Profile Tags</relationshipLabel>
        <relationshipName>Contact_Profile_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Profile Tag</label>
    <nameField>
        <displayFormat>CCT-{yy}{mm}{0}</displayFormat>
        <label>Community Profile Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Profile Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommunityBatchHelper.cls
public with sharing class CommunityBatchHelper {

	public static Boolean migrateField(List<SObject> records, Map<String, String> fieldMapping) {
		try {
			for (String fld : fieldMapping.keySet()) {
				String mappedFld = fieldMapping.get(fld);
				for (SObject record : records) {
					if (record.get(fld) != null) {
						record.put(mappedFld, record.get(fld));
					}
				}
			}
			update records;
		} catch(Exception e) {
			System.debug(e.getMessage());
			return false;
		}
		return true;
	}

	public static void startMigrateProfileTagContactField() {
		String prefix = CommunityUtils.getPackagePrefix();
		String queryString = 'SELECT Id, {0}Contact__c, {0}Related_Contact__c FROM {0}Community_Profile_Tag__c WHERE {0}Related_Contact__c = null AND {0}Contact__c != null';
		String query = String.format(queryString, new List<String>{ prefix });
		Map<String, String> params = new Map<String, String> { prefix+'Contact__c' => prefix+'Related_Contact__c' };

		CommunityBatch b = new CommunityBatch(query, 'migrateField', params);
		Database.executeBatch(b);
	}

}